
import { RootConstruct } from "constructs";
import { ChartProps } from "cdk8s";
import {
  INetworkPolicyPeer, Namespaces, NetworkPolicyIpBlock, NetworkPolicyPort, NetworkPolicyRule,
  PersistentVolumeClaimProps, Pods,
} from "cdk8s-plus-33";

const root = new RootConstruct();

export interface ShanoirCredentials {
  readonly username: string;
  readonly password: string;
}

/** Parameters for accessing a Mysql/Mariadb/Posgresql database */
export interface ShanoirDatabaseProps extends ShanoirCredentials {
  readonly db: string;
  readonly host: string;
  /** egress peer
   *
   * see {@link ShanoirNetworkPoliciesProps}
   */
  readonly peer?: ShanoirNetworkPolicyPeer;
  readonly port?: number;
}

/** Default values for {@link ShanoirSmtpProps} */
export const shanoirSmtpDefaults = {
  port: 25,
  auth: undefined,
  starttls: "disabled" as "disabled",
};

/** SMTP configuration for outgoing mails */
export interface ShanoirSmtpProps {

  /** relay hostname/ip
   *
   * Leave it empty when using the mailpit service (see {@link mailpit})
   */
  readonly host?: string;

  /** egress peer
   *
   * see {@link ShanoirNetworkPoliciesProps}
   */
  readonly peer?: ShanoirNetworkPolicyPeer;

  /** relay TCP port
   *
   * @default see {@link shanoirSmtpDefaults}
   */
  readonly port?: number;

  /** smtp user account
   *
   * @default no authentication
   */
  readonly auth?: ShanoirCredentials;

  /** STARTTLS configuration
   *
   * @default see {@link shanoirSmtpDefaults}
   */
  readonly starttls?: "disabled" | "optional" | "required";

  /** Configuration of the Mailpit service
   *
   * If set, this chart will include a Mailpit SMTP server for catching outgoing emails.
   * It will be used when {@link ShanoirSmtpProps.host} is undefined.
   *
   * Mailpit is a dummy SMTP server for testing purpose. DO NOT USE IT IN PRODUCTION.
   * https://mailpit.axllent.org/
   */
  readonly mailpit?: ShanoirMailpitProps;

  /** default sender address */
  readonly fromAddress: string;
}

/** Configuration of the Mailpit service */
export interface ShanoirMailpitProps {
  /** Ingress host name
   *
   * If set, the shanoir ingress will include a rule to expose the Mailpit Web UI at this hostname.
   *
   * Note: the UI is unauthenticated. DO NOT EXPOSE IT TO THE INTERNET.
   */
  readonly host?: string;
}

/** Default values for {@link ShanoirVipProps} */
export const shanoirVipDefaults = {
  url: "https://vip.creatis.insa-lyon.fr",
  peer: NetworkPolicyIpBlock.ipv4(root, "vip-ip", "134.214.205.86/32"),
  clientSecret: "SECRET",
  serviceEmail: "",
};

/** VIP (Virtual Imaging Platform) client configuration */
export interface ShanoirVipProps {
  readonly url: string;
  /** egress peer
   *
   * see {@link ShanoirNetworkPoliciesProps}
   */
  readonly peer?: ShanoirNetworkPolicyPeer;
  readonly clientSecret: string;
  readonly serviceEmail: string;
}

/** List of keys expected in {@link ShanoirNGProps.volumeClaims} */
export const shanoirVolumes = [
  // medical data
  "datasets-data",
  "dcm4chee-arc-storage-data",
  "preclinical-data",
  "studies-data",

  // databases
  "database-data",
  "dcm4chee-database-data",
  "keycloak-database-data",

  // logs
  "logs",
  "dcm4chee-logs",
  "keycloak-logs",

  // disposable data (temporary data, indexes, ...)
  "bids-data",
  "rabbitmq-data",
  "solr-data",
  "tmp",

  // these volume store configuration data that is autogenerated from the environment variables
  // if not provided, they will be mounted from an ephemeral volume
  "dcm4chee-arc-wildfly-data",
  "dcm4chee-ldap-data",
  "dcm4chee-sldap-data",
];


/** List of mysql databases to be provide in {@link ShanoirNGProps.mysqlDatabases} */
export const shanoirMysqlDatabases = [
  "datasets",
  "import",
  "keycloak",
  "migrations",
  "preclinical",
  "studies",
  "users",
];

export const shanoirPostgresqlDatabases = [
  "dcm4chee",
];

export const defaultUids = {
  "database": 510,
  "rabbitmq": 511,
  "ms":  512,
  "nifti-conversion": 512,
  "keycloak-database": 513,
  "solr": 514,
  "mailpit": 600,
  "keycloak": 1000,
  // Note: the dcm4chee images do not support running as an arbitary user, they must be run as
  // root and switch to an hardcoded uid at startup:
  // - dcm4chee-database: 999
  // - dcm4chee-ldap: 1021
  // - dcm4chee-arc: 1023
  "nobody": 65535,
}


/** Default values for {@link ShanoirNGProps} */
export const shanoirNGDefaults = {
  version: "develop",
  instanceName: "",
  instanceColor: "",
  allowedAdminIps: [],
  smtp: shanoirSmtpDefaults,
  vip: shanoirVipDefaults,
  createNamespace: true,
  uids: defaultUids,
  shutdownHour: 0,
  continuanceHour: 0,
  init: false,
};

/** get the official repository for a given version
 *
 * Releases are hosted on the official 'shanoir-ng` repository and development versions (named
 * `develop` or a git commit id) are hosted in a side repository (`shanoir-deploy`).
 */
export function defaultDockerRepository(version: string): string
{
  return /^(develop|[0-9a-f]{40})$/.test(version) ? "ghcr.io/fli-iam/shanoir-deploy"
                                                  : "ghcr.io/fli-iam/shanoir-ng";
}

export const shanoirIngressDefaults = {
  peer: new Pods(root, "nginx-pods", [], {"app.kubernetes.io/component": "controller"},
                 new Namespaces(root, "nginx-ns", [], ["ingress-nginx"])),
}

export interface ShanoirIngressProps {
  /** Ingress class */
  readonly className?: string

  /** ingress peer
   *
   * see {@link ShanoirNetworkPoliciesProps}
   *
   * @default matches the nginx ingress controller (pods tagged "app.kubernetes.io/component:
   *          controller" in the "ingress-nginx" namespace
   */
  readonly peer?: ShanoirNetworkPolicyPeer;

  /** TLS certificate (PEM format)
   *
   * It must cover the two domains listed in {@link ShanoirNGProps.url} and {@link
   * ShanoirNGProps.viewerUrl}.
   *
   * If unset then it is up to the ingress controller to generate a self-signed certificate.
   */
  readonly tlsCrt?: string;

  /** TLS key (PEM format) 
  *
  * see {@link tlsCrt}
  * */
  readonly tlsKey?: string;

  /** Expose the keycloak admin console and the master realm in the ingress rules
   *
   * By default the ingress rule only exposes the routes to the shanoir-ng realm (for security
   * reasons).
   */
  readonly exposeKeycloakAdminConsole?: boolean; 
};

/** Default values for {@link ShanoirViewerMaxNumRequestsProps} */
export const shanoirViewerMaxNumRequestsDefaults = {
  interaction: 40,
  thumbnail: 20,
  prefetch: 20,
}

export interface ShanoirViewerMaxNumRequestsProps
{
  readonly interaction?: number,
  readonly thumbnail?: number,
  readonly prefetch?: number,
}

export type ShanoirNetworkPolicyPeer = string | INetworkPolicyPeer;

/** Specification of an authorized network flow
 *
 * This structure represents an authorized network flow between a source `src` and a destination
 * `dst`. It is used to generate the ingress/egress rules in the cdk8s network policies.
 *
 * "src" and "dst" may be either a INetworkPeer object representing an external source or
 * destination or a string identifying a workload (deployment or job) created by
 * {@link ShanoirNGChart.createDeployment()} or {@link ShanoirNGChart.createJob()} and stored in
 * {@link ShanoirNGChart.workloads}.
 *
 * If "src" is a string, then an egress rule with "{peer: flow.dst, ports: flow.ports}" will be
 * added to the policy applied to the source pods.
 *
 * If "dst" is a string, then an ingress rule with "{peer: flow.src, ports: flow.ports}" will be
 * added to the policy applied to the destination pods.
 *
 * @example rule allowing mysql connections from 192.0.2.0/24 to the "database" deployment
 *
 * import { NetworkPolicyIpBlock, NetworkPolicyPort } from "cdk8s-plus-33";
 *
 * const rule = {
 *    src: NetworkPolicyIpBlock.ipv4(app, "test-net-1", "192.0.2.0/24"),
 *    dst: "database",
 *    ports: [NetworkPolicyPort.tcp(3306)],
 * };
 */
export interface ShanoirNetworkPolicyFlow
{
  readonly src?: ShanoirNetworkPolicyPeer,
  readonly dst?: ShanoirNetworkPolicyPeer,
  readonly ports: NetworkPolicyPort[],
}

export const shanoirNetworkPoliciesDefaults = {
  ingress: true,
  egress: true,
  extraFlows: [],
  egressDnsRule: {
    peer: new Pods(root, "dns-pods", [], {"k8s-app": "kube-dns"},
                   new Namespaces(root, "dns-ns", [], ["kube-system"])),
    ports: [NetworkPolicyPort.udp(53), NetworkPolicyPort.tcp(53)],
  },
}

/** Configuration of the network policies
 *
 * Every workload (deployment or job) instantiated by the ShanoirNGChart comes along with a network
 * policy that implements ingress and egress filtering.
 *
 * By befault both ingress and egress rules are generated. They can be independently enabled or
 * disabled with {@link ingress} and {@link egress}.
 *
 * The generated rules only cover the flows that are strictly needed to operate shanoir. Additional
 * rules can be configured in {@link extraFlows}.
 *
 * Interactions with external services (i.e. services that are not part of ShanoirNGChart) are
 * addressed but they require the config for these services to provide a value for the "peer"
 * property.  Especially the generation of ingress rules will fail if
 * {@link ShanoirIngressProps.peer} is undefined and the generation of egress rules will fail if any
 * of {@link ShanoirDatabaseProps.peer}, {@link ShanoirSmtpProps.peer} or
 * {@link ShanoirVipProps.peer} is undefined.
 */
export interface ShanoirNetworkPoliciesProps {
  /** generate ingress rules
   *
   * If disabled (not recommended), the pods will not have any ingress policy and will be reachable
   * from any cluster ip.
   *
   * @default true
   */
  readonly ingress?: boolean;

  /** generate egress rules
   *
   * If disabled (not recommended), the pods will not have any egress folicy and will be able to
   * reach any ip.
   *
   * @default true
   */
  readonly egress?: boolean;

  /** additional authorized flows */
  readonly extraFlows?: ShanoirNetworkPolicyFlow[];

  /** egress rule for reaching the dns resolver
   *
   * This is the rule giving access to dns resolver needed for service discovery between the shanoir
   * pods.
   *
   * @default UDP and TCP port 53 to the dns resolver of the cluster
   *          (pods tagged "k8s-app: kube-dns" in the "kube-system" namespace)
   */
  readonly egressDnsRule?: NetworkPolicyRule;
}

/** Configuration of a shanoir instance */
export interface ShanoirNGProps extends ChartProps {

  /** Version of shanoir to be deployed (tag of the OCI images)
   *
   * @default use the latest release
   */
  readonly version?: string;

  /** Main url of this shanoir instance */
  readonly url: string;

  /** Url of the OHIF viewer */
  readonly viewerUrl: string;

  /** Set the maximum number of concurrent requests sent by the OHIF viewer
   *
   * see `maxNumRequests`
   * in https://docs.ohif.org/configuration/configurationFiles#configuration-options
   *
   * @default see {@link shanoirViewerMaxNumRequestsDefaults}
   */
  readonly viewerMaxNumRequests?: ShanoirViewerMaxNumRequestsProps;

  /** Name of this shanoir instance (displayed in the side panel) */
  readonly instanceName?: string;

  /** CSS color of this shanoir instance */
  readonly instanceColor?: string;

  /** Name of the administrator (for signing outgoing e-mails) */
  readonly adminName: string;

  /** E-mail of the administrator (for signing outgoing e-mails) */
  readonly adminEmail: string;

  /** Name of the OCI repository providing the shanoir images
   *
   * If unset, the images will be pulled from the official shanoir repository.
   *
   * @default see {@link defaultDockerRepository}
   */
  readonly dockerRepository?: string;

  /** Mysql databases parameters
   *
   * If unset, this chart will include a mysql deployment for hosting the databases.
   *
   * Otherwise the object must contain all keys listed in {@link shanoirMysqlDatabases}
   * (except 'keycloak' which may be omitted when using an external keycloak server)
   */
  readonly mysqlDatabases?: {[key: string]: ShanoirDatabaseProps};

  /** Postgresql databases 
   *
   * If unset, this chart will include a postgresql deployment for hosting the databases.
   *
   * Otherwise the object must contain all keys listed in {@link shanoirPostgresqlDatabases}
   */
  readonly postgresqlDatabases?: {[key: string]: ShanoirDatabaseProps};

  /** SMTP parameters for outgoing emails */
  readonly smtp: ShanoirSmtpProps;

  /** List of client IP address or networks from which admin accounts are allowed to log in.
  *
  * @example ["192.0.2.1", "2001:db8:1::/64"]
  */
  readonly allowedAdminIps?: Array<string>;

  /** Url of the keycloak server (if external)
  *
  * If undefined, this chart will include a keycloak deployment reachable at `${this.url}/auth/`
  */
  readonly keycloakUrl?: string;

  /** Internal url of the keycloak server
   *
   * This parameter may contain an alternate URL to reach the keycloak server from the shanoir
   * microservices. It must not be set if {@link keycloakUrl} is undefined.
   *
   * If undefined, the deployment will use the same value as {@link keycloakUrl}.
   */
  readonly keycloakInternalUrl?: string;

  /** Keycloak account (master realm) for managing users */
  readonly keycloakCredentials: ShanoirCredentials;

  /** VIP (Virtual Imaging Platform) client configuration
  *
  * Used by the CARMIN-API-CLIENT in the front of shanoir-ng to query for pipelines
  */
  readonly vip?: ShanoirVipProps;

  /** Volumes claims for this shanoir instance
  *
  * See {@link shanoirVolumes} for the full list of volumes for which a volume claim is expected.
  *
  * The following volume claims may be omitted
  * - `dcm4chee-arc-wildfly-data`, `dcm4chee-ldap-data` and `dcm4chee-sldap-data` are used to store
  *   config files autogenerated from environment variables by the `dcm4che/dcm4chee-arc-psql` and
  *   `dcm4che/slapd-dcm4chee` docker images. If the volume claims are omitted, then they will be
  *   mounted from an ephemeral volume.
  * - `database-data` is not used when {@link mysqlDatabases} is set
  * - `keycloak-database-data` is not used when {@link mysqlDatabases} or {@link keycloakUrl} is set
  * - `dcm4chee-database-data` is not used when {@link postgresqlDatabases} is set
  */
  readonly volumeClaims: { [key: string]: PersistentVolumeClaimProps};

  /** Ingress configuration */
  readonly ingress: ShanoirIngressProps;

  /** Network policies configuration */
  readonly networkPolicies?: ShanoirNetworkPoliciesProps;

  /** Create the kubernetes namespace
   *
   * @default see {@link shanoirNGDefaults}
   */
  readonly createNamespace?: boolean;

  /** uid/gid to be assigned for each workload
   *
   * The default security context generated by cdk8s forbids running containers as root.
   *
   * This hashmap list the uid (also the gid which is set to the samevalus) to be used in each pod
   * created by {@link ShanoirNGChart.createDeployment()} and {@link ShanoirNGChart.createJob}.
   * The hashmap keys are the values provided for the 'name' arguments of these function.
   *
   * @default see {@link shanoirNGDefaults}
   */
  readonly uids?: {[key:string]: number};

  /** start time of the daily unavailability period
   *
   * This variable, along with {@link continuanceHour}, may be used to indicate a daily time period
   * when this shanoir instance is not available (eg: for maintainance purpose). Shanoir will avoid
   * scheduling VIP jobs during that period.
   *
   * @example `{shutdownHour: 1, continuanceHour: 2}` means that this shanoir instance may not be
   * available between 1am and 2am every night
   */
  readonly shutdownHour?: number;

  /** end time of the daily unavailability period
   *
   * see {@link shutdownHour}
   */
  readonly continuanceHour?: number;

  /** Flag for initialising a new shanoir instance
   *
   * Set this flag to 'true' when deploying a new shanoir instance.
   *
   * This will generate an additional chart with a name starting with 'danger-init-' and providing
   * the deployments and jobs to carry out the initial migrations.
   *
   * This additional chart performs destructive operations (especialy the databases are wiped out).
   * It must never be run on a pre-existing production instance.
   */
  readonly init?: boolean;
}
